# Generated by Django 3.2.5 on 2021-08-24 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expencecategory',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
