# Generated by Django 3.2.5 on 2021-08-24 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_alter_expencecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
