# Generated by Django 3.2.5 on 2021-08-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_alter_incomecategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expencecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
